// Define Actions
export const INIT_USER = 'INIT_USER'
export const LOAD_FORMS = 'LOAD_FORMS'
export const LOAD_SUBMISSIONS = 'LOAD_SUBMISSIONS'
export const LOAD_PROFILE = 'LOAD_PROFILE'
export const CREATE_FORM = 'CREATE_FORM'
export const RECEIVE_SUBMISSION = 'RECEIVE_SUBMISSION'
export const UPDATE_FORM = 'UPDATE_FORM'
export const DELETE_FORM = 'DELETE_FORM'
export const ERROR = 'ERROR'
